# -*- coding: utf-8 -*-
"""bolao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/134BuJwxHU1y6SHba-nalytXQiXbJgFYd
"""

import math

def resultado(g1, g2):
    if g1>g2:
        res = "1"
    elif g2>g1:
        res = "2"
    else:
        res = "E"
    return(res)

def npts_tecgraf(gp1, gp2, gr1, gr2):
    rp = resultado(gp1, gp2)
    rr = resultado(gr1, gr2)
    if (rp == rr):
        npts = 5
        if gp1 > gp2:
            if (gp1 == gr1):
                npts += 3
            if (gp2 == gr2):
                npts += 2
        elif gp1 < gp2:
            if (gp1 == gr1):
                npts += 2
            if (gp2 == gr2):
                npts += 3 
        else:
            if (gp1 == gr1):
                npts += 5
    elif (gp1 == gr1) or (gp2 == gr2):
        npts = 1
    else:
        npts = 0
    return(npts)

def npts_caetano(gp1, gp2, gr1, gr2):
    rp = resultado(gp1, gp2)
    rr = resultado(gr1, gr2)
    npts = 0
    if (rp == rr):
        npts += 3
    if (gp1 == gr1):
        npts += 1
    if (gp2 == gr2):
        npts += 1  
    if ((gp1 - gp2) == (gr1 - gr2)):
        npts += 1
    return(npts)

def npts_ibge(gp1, gp2, gr1, gr2):
    rp = resultado(gp1, gp2)
    rr = resultado(gr1, gr2)
    npts = 0
    if (rp == rr):
        npts += 5
    if (gp1 == gr1) and (gp2 == gr2):
        npts += 3
    return(npts)

def npts_eduardo(gp1, gp2, gr1, gr2):
    npts_score = 10
    npts_resultado = 4
    npts_resultado_score = 6 
    rp = resultado(gp1, gp2)
    rr = resultado(gr1, gr2)
    if (gp1 == gr1)  and (gp2==gr2):
        return (npts_score)
    elif (rp ==rr):
        if (gp1 == gr1) or (gp2 == gr2):
            return (npts_resultado_score)
        else:
            return(npts_resultado)
    else:
        return(0)

def npts_exato(gp1, gp2, gr1, gr2):
    if (gp1 == gr1)  and (gp2==gr2):
        return(1)
    else:
        return(0)

def npts(gp1, gp2, gr1, gr2):
    return(npts_tecgraf(gp1, gp2, gr1, gr2))

def prob_res(i, j, a1, a2, d1, d2):
    l1 = a1/d2
    l2 = a2/d1
    return(math.exp(-l1)*math.exp(-l2)*math.pow(l1, i)*math.pow(l2, j)/math.factorial(i)/math.factorial(j))

def Epts(gp1, gp2, a1, a2, d1, d2):
    E = 0
    for i in range(5):
        for j in range(5):
            E += npts(gp1, gp2, i, j) * prob_res(i, j, a1, a2, d1, d2)
    return(E)

def melhor_resultado(a1, a2, d1, d2):
    Emax = 0
    imax = 0
    jmax = 0
    for i in range(5):
        for j in range(5):
            E = Epts(i, j, a1, a2, d1, d2)
            if E > Emax:
                Emax = E
                imax = i
                jmax = j
    return([imax, jmax])

def bolao_copa():
    sel=[""]
    sel_cod=[]
    sel_abrev =[""]
    alfa=[]
    beta=[]
    ordem_alfabetica = [0 for i in range(33)]
    grupos=[[] for i in range(8)]
    f=open("grupos_selecoes.txt", encoding = "utf-8")
    for linha in f:
        sel_abrev.append(linha.split('\t')[0])
        sel.append(linha.split('\t')[1])
        cod = int(linha.split('\t')[3])
        sel_cod.append(cod)
        ordem =int(linha.split('\t')[4])
        ordem_alfabetica[ordem-1]=cod
    
    
    
    f.close()
    f=open("params_ordenado.txt")
    for linha in f:
        alfa.append(float(linha.split('\t')[0]))
        beta.append(float(linha.split('\t')[1]))
        
    f.close()
    
    f = open("palpites_finais.txt", "w")
    Grupos = ["A", "B", "C", "D", "E", "F", "G", "H"]
    jogos = [[0, 1], [2, 3], [0, 2], [1, 3], [0, 3], [1,2]]
    if True:
        for g in range(8):
            f.write("Grupo "+ Grupos[g] + "\n")
            for j in range(6):
                t1 = jogos[j][0] + 4*g + 1
                t2 = jogos[j][1] + 4*g + 1
                alfa1 = alfa[t1-1]
                alfa2 = alfa[t2-1]
                beta1 = beta[t1-1]
                beta2 = beta[t2-1]
                print(t1, t2, alfa1, alfa2, beta1, beta2)
                res = melhor_resultado(alfa1, alfa2, beta1, beta2)
                f.write(sel_abrev[t1] + " " + str(res[0]) + " X "+ str(res[1])+ " "+ sel_abrev[t2] + "\n")
    
    #oitavas = [[4, 5], [6,1], [9,13], [15, 12], [17, 22], [23, 18], [25, 32], [31,28]]
    #quartas = [[4,9], [17,25], [1, 15], [23, 28]]
    #semis = [[9, 25], [15,28]]
    #finais = [[25, 28], [9, 15]]
    #for j in finais:
    #    t1 = j[0]
    #   t2 = j[1]
    #    alfa1 = alfa[t1-1]
    #    alfa2 = alfa[t2-1]
    #    beta1 = beta[t1-1]
    #    beta2 = beta[t2-1]
    #    print(t1, t2, alfa1, alfa2, beta1, beta2)
    #    res = melhor_resultado(alfa1, alfa2, beta1, beta2)
    #    f.write(sel_abrev[t1] + " " + str(res[0]) + " X "+ str(res[1])+ " "+ sel_abrev[t2] + "\n")    
    f.close()

bolao_copa()