# -*- coding: utf-8 -*-
"""scrapy_txt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CdLLFq5pv3Y4Mht-k_TaeL3NliRZjJ6r
"""

import pandas as pd
import datetime as dt
import numpy as np

#le os arquivos com os jogos e com os números correspondentes as seleçoes
results = pd.read_excel('/content/ResultadosPosCopa.xlsx',header=None)
selecoes = pd.read_excel('/content/selecoes_conf.xlsx',header=None)

#associa a cada seleçao seu numero
selecoes_dict = {}
for i in selecoes.index:
  selecoes_dict[selecoes[1].iloc[i]]=selecoes[0].iloc[i]

campeonato = list(set(results[5]))

#lista dos campeonatos com o peso 3(eliminatorias p copa)
eliminatorias = ['CONMEBOL–UEFA Cup of Champions','AFC Asian Cup','African Cup of Nations','UEFA Nations League','FIFA World Cup qualification','CONCACAF Nations League']

#determina o peso de cada campeonato
#amistosos - peso 1
#copas dos paises e campeonatos internos - peso 2.5
#qualificatorias para a copa - peso 3
#copa do mundo ainda nao ta inclusa porque ainda nao tem jogos, vou poder depois
campeonato_lista = []
for i in results[5]:
  if i=='Friendly':
    campeonato_lista.append(1)
  elif i in eliminatorias:
    campeonato_lista.append(3)
  else:
    campeonato_lista.append(2.5)

#associa os gols as selecoes na ordem do arquivo
sel1 = []
for i in results[1]:
  sel1.append(selecoes_dict[i])
sel2 = []
for i in results[2]:
  sel2.append(selecoes_dict[i])

#dicionário com os dados na ordem 
dic = {'sel1':[],'gols1':[],'gols2':[],'sel2':[],'data':[],'peso':[]}

#define o novo formato da data
data_timestamp = []
for i in results[0]:
  data_timestamp.append(i.toordinal())

#associa a cada termo do dicionário seus valores
dic['data']=data_timestamp
dic['gols1']=list(results[3])
dic['gols2']=list(results[4])
dic['sel1']=sel1
dic['sel2']=sel2
dic['peso']=campeonato_lista

#cria um dataframe com todos os valores ja selecionados
dic_df = pd.DataFrame(dic)

#faz um arquivo em txt com o dataframe criado
with open('internacionais_2022.txt', 'a') as f:
    df_string = dic_df.to_string(index=False)
    f.write(df_string)