# -*- coding: utf-8 -*-
"""simul_copa_inicial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ygJpArKtcEcDZ0fvimzYhgF8CqDeTk4z
"""

import random, math, operator
import webutils

def gen_gols_Jogo(alfa, beta):
    lamb = alfa/beta
    g = 0
    x = -math.log(1- random.uniform(0, 1))
    while( x < lamb):
      x = x -math.log(1 - random.uniform(0, 1))
      g = g+1
    return(g)

#Gols marcados durante uma prorrogacao, poisson((alfa/beta)/3) 
def gen_gols_pror(alfa, beta):
    lamb = (alfa/beta)/3.
    g = 0
    x = -math.log(1- random.uniform(0, 1))
    while( x < lamb):
      x = x -math.log(1 - random.uniform(0, 1))
      g = g+1
    return(g)

def penaltis(time1, time2):
    if (random.uniform(0,1)>=0.5):
        return(time1)
    else:
        return(time2)

#grupo-> vetor com as selecoes do grupo    
#gera a clasificacao final baseada em uma realizacao aleatoria com os parametros
#de ataque e defesa estimados
def gerar_class (grupo, alfa, beta):
    
    #print (grupo)
    sel_ids= [0 for i in range(32)]
    cod=0
    for n in grupo:
        sel_ids[n-1]=cod
        cod+=1
    ajogar=[0 for j in range(6)]
    ajogar[0]=[grupo[0],grupo[1]]
    ajogar[1]=[grupo[0],grupo[2]]
    ajogar[2]=[grupo[0],grupo[3]]
    ajogar[3]=[grupo[1],grupo[2]]
    ajogar[4]=[grupo[1],grupo[3]]
    ajogar[5]=[grupo[2],grupo[3]]
    
    cl = [[0 for i in range(5)] for j in range(4)]
    for i in range(len(grupo)):
       cl[i][0] = grupo[i]       
    for i in range(6):
       t1 = sel_ids[ajogar[i][0]-1]
       t2 = sel_ids[ajogar[i][1]-1]
       g1 = gen_gols_Jogo(alfa[ajogar[i][0]-1], beta[ajogar[i][1]-1])
       g2 = gen_gols_Jogo(alfa[ajogar[i][1]-1], beta[ajogar[i][0]-1])
       cl[t1][3] += g1
       cl[t1][2] += (g1 - g2)
       cl[t2][3] += g2
       cl[t2][2] += (g2 - g1)
        #Caso os tres criterios deem empatados(pontos, saldo de gols e gols marcados)
       cl[t1][4]=random.uniform(0,1)
       cl[t2][4]=random.uniform(0,1)
       if (g1 > g2):
            cl[t1][1] += 3
       elif (g2 > g1):
            cl[t2][1] += 3
       else:
            cl[t1][1] += 1
            cl[t2][1] += 1
       #print([t1, g1, g2, t2])
        
    for col in [4, 3, 2, 1]:
        cl = sorted(cl, key = operator.itemgetter(col), reverse = True)
    #print(cl)
    return(cl)

#Primeira fase geral, ou seja, com oito grupos
def Primeira_Fase(grupos,alfa,beta):
    n_grupos=len(grupos)
    matriz_class=[]
    for n in range(n_grupos):
        matriz_class.append(gerar_class(grupos[n], alfa, beta))
    ajogar=[]
    for n in range(n_grupos):
        if (n%2==0):
            ajogar.append([matriz_class[n][0][0],matriz_class[n+1][1][0]])
        else:
            ajogar.append([matriz_class[n][0][0],matriz_class[n-1][1][0]])
    ajogarcerto=[]
    ajogarcerto.append(ajogar[0])
    ajogarcerto.append(ajogar[2])
    ajogarcerto.append(ajogar[4])
    ajogarcerto.append(ajogar[6])
    ajogarcerto.append(ajogar[1])
    ajogarcerto.append(ajogar[3])
    ajogarcerto.append(ajogar[5])
    ajogarcerto.append(ajogar[7])
    
    return(ajogarcerto)

def Primeira_Fase_Jogada(grupos,alfa,beta):
    n_grupos=len(grupos)
    matriz_class=[]
    
    ajogar=[]
    ajogar.append([4, 5])
    ajogar.append([6, 1])
    ajogar.append([9, 13])
    ajogar.append([15, 12])
    ajogar.append([17, 22])
    ajogar.append([23, 18])
    ajogar.append([25, 32])
    ajogar.append([31, 28])
    ajogarcerto=[]
    ajogarcerto.append(ajogar[0])
    ajogarcerto.append(ajogar[2])
    ajogarcerto.append(ajogar[4])
    ajogarcerto.append(ajogar[6])
    ajogarcerto.append(ajogar[1])
    ajogarcerto.append(ajogar[3])
    ajogarcerto.append(ajogar[5])
    ajogarcerto.append(ajogar[7])
    
    return(ajogarcerto)

def mata_mata(ajogar,alfa,beta):
    vencedor=[]
    ajogar_novo=[]
    for jogo in ajogar:
        t1 = jogo[0]-1
        t2 = jogo[1]-1
        g1 = gen_gols_Jogo(alfa[t1], beta[t2])
        g2 = gen_gols_Jogo(alfa[t2], beta[t1])
        if(g1==g2):
            gp1 = gen_gols_pror(alfa[t1], beta[t2])
            gp2 = gen_gols_pror(alfa[t2], beta[t1])
            if (gp1==gp2):
                vencedor.append(penaltis(t1+1,t2+1))
            elif(gp1>gp2):
                vencedor.append(t1+1)
            else:
                vencedor.append(t2+1)
        elif(g1>g2):
            vencedor.append(t1+1)
        else:
            vencedor.append(t2+1)
            
    vencedor.reverse()
    if(len(ajogar)>1):
        for i in range(int(len(ajogar)/2)):
            ajogar_novo.append([vencedor.pop(),vencedor.pop()])
    else:
        ajogar_novo=vencedor
    return(ajogar_novo)

#Retorna a final e a disputa da terceira colocacao    
def Semifinais(ajogar,alfa,beta):
    ajogar_finais = mata_mata(ajogar,alfa,beta)
    if (ajogar_finais[0][0]==ajogar[0][0]):
        time_terc_1=ajogar[0][1]
    else:
        time_terc_1=ajogar[0][0]
    
    if (ajogar_finais[0][1]==ajogar[1][0]):
        time_terc_2=ajogar[1][1]
    else:
        time_terc_2=ajogar[1][0]
        
    ajogar_terc=[[time_terc_1,time_terc_2]]
    return([ajogar_finais,ajogar_terc])

#Retorna freq=[[1grupo,2grupo,oitavas,quartas,semi,terceiro,segundo,campeao],...]
def Simul_Copa(grupos, alfa, beta, rep):
    
    freq=[[0 for n in range(8)] for i in range(32)]
    
    for k in range(rep):
        oitavas=Primeira_Fase(grupos,alfa,beta)
  
        #oitavas=Primeira_Fase_Jogada(grupos,alfa,beta)
        #print(oitavas)
        
        for jogo in oitavas:
            freq[jogo[0]-1][0]+=1./rep
            freq[jogo[1]-1][1]+=1./rep
            freq[jogo[0]-1][2]+=1./rep
            freq[jogo[1]-1][2]+=1./rep
        
        quartas=mata_mata(oitavas,alfa,beta)
        #quartas = []
        #quartas.append([4,9])
        ##uartas.append([17, 25])
        #quartas.append([1,15])
        #quartas.append([23,28])
        for jogo in quartas:
            freq[jogo[0]-1][3]+=1./rep
            freq[jogo[1]-1][3]+=1./rep
        #print(quartas)
            
        semi=mata_mata(quartas,alfa,beta)
        #semi = []
        #semi.append([9,25])
        #semi.append([15,28])
        for jogo in semi:
            freq[jogo[0]-1][4]+=1./rep
            freq[jogo[1]-1][4]+=1./rep
        #print(semi)
        
        ult_jogos=Semifinais(semi,alfa,beta)
        
        print(ult_jogos)
        
        final=ult_jogos[0]
        terc_col=ult_jogos[1]
        
        #final =[[9, 15]]
        #terc_col = [[25, 28]]
        
        terceiro=mata_mata(terc_col,alfa,beta)
        
        freq[terceiro[0]-1][5]+=1./rep
        
        primeiro=mata_mata(final,alfa,beta)
            
        freq[primeiro[0]-1][7]+=1./rep
        
        if(primeiro[0]==final[0][0]):
            segundo=final[0][1]
        else:
            segundo=final[0][0]
        
        freq[segundo-1][6]+=1./rep
        
    return (freq)

def format_prob(p):
    if p < 0.5:
        s = "< 0,5"
    else:
        s = "%3.0f" % p
    return(s)

def Simulador_Copa(rep):
    sel=[""]
    sel_cod=[]
    sel_abrev =[""]
    alfa=[]
    beta=[]
    ordem_alfabetica = [0 for i in range(33)]
    grupos=[[] for i in range(8)]
    f=open("grupos_selecoes.txt", encoding = "utf-8")
    for linha in f:
        sel_abrev.append(linha.split('\t')[0])
        sel.append(linha.split('\t')[1])
        cod = int(linha.split('\t')[3])
        sel_cod.append(cod)
        ordem =int(linha.split('\t')[4])
        ordem_alfabetica[ordem-1]=cod
    
    
    
    f.close()

    f=open("params_ordenado.txt")
    for linha in f:
        alfa.append(float(linha.split('\t')[0]))
        beta.append(float(linha.split('\t')[1]))
        
    f.close()
    count=0
    for i in range(8):
        grupo= [0 for i in range(4)]
        for j in range(4):
            grupo[j]=sel_cod[j+count]
        grupos[i]=grupo
        count+=4
    print(alfa)
    print(beta)
    print(sel)
    print(sel_cod)
    print(sel_abrev)
    print(grupos)
    prob=Simul_Copa(grupos, alfa, beta, rep)
    prob_form = [["" for i in range(5)] for j in range(32)]
    for j in range(32):
        prob_form[j][0] = format_prob(100*prob[j][7]) 
        prob_form[j][1] = format_prob(100*prob[j][2])
        prob_form[j][2] = format_prob(100*prob[j][3])
        prob_form[j][3] = format_prob(100*prob[j][4])
        prob_form[j][4] = format_prob(100*(prob[j][6]+ prob[j][7])) 


    #g = open("primeira_fase.htm", "w", encoding = "latin-1")
    #webutils.Pagina_Grupos(grupos, alfa, beta, sel, g)
    #webutils.Pagina_Visual_Grupos(alfa, beta, grupos, sel, sel_abrev, g)
    webutils.Previsoes_1fase(grupos, alfa, beta, sel, sel_abrev)
    webutils.Chances(sel, sel_abrev, ordem_alfabetica, prob_form)
    #g.close()
    
#    g = open("disputas/probabilidades.htm")
#    Pagina_Probabilidades(sel, prob)
#    g.close()
    
    p=open("Probabilidades.txt","w")
    for i in range(32):
        p.write(sel[i+1])
        p.write("\t")
        for j in range(8):
            p.write(str(prob[i][j]))
            p.write("\t")
        p.write('\n')
    p.close()
    
    return (prob)

Simulador_Copa(1)